name: employee-payroll-service-local
services:
  postgresql:
    image: postgres:16
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - "./storage/postgresql/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employee_payroll_db
      POSTGRES_PORT: 5432

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - "./storage/rabbitmq/data:/var/lib/rabbitmq"

  redis:
    image: redis:6
    restart: on-failure
    entrypoint:
      - "redis-server"
    volumes:
      - "./storage/redis/conf:/usr/lib/redis/conf"
      - "./storage/redis/modules:/usr/lib/redis/modules"
      - "./storage/redis/data:/data"
    ports:
      - "6379:6379"